insert into public.product(name,price) values('HTC EVO 4G',6000);
insert into public.product(name,price) values('Motorola Cliq 2',5900);
insert into public.product(name,price) values('Motorola i886',5800);
insert into public.product(name,price) values('LG Axis',5700);
insert into public.product(name,price) values('Samsung Gem',5600);
insert into public.product(name,price) values('Huawei IDEOS X5',5500);
insert into public.product(name,price) values('Toshiba REGZA IS04',5400);
insert into public.product(name,price) values('Sharp Galapagos 005SH',5300);
insert into public.product(name,price) values('HTC Inspire 4G',5200);
insert into public.product(name,price) values('Dell Venue',5100);
insert into public.product(name,price) values('HTC thunderbolt',5000);
insert into public.product(name,price) values('HTC gratia',4900);
insert into public.product(name,price) values('LG Optimus V',4800);
insert into public.product(name,price) values('Samsung galaxy S 4G',4700);
insert into public.product(name,price) values('Millennius iNoid',4600);
insert into public.product(name,price) values('Samsung Galaxy Indulge',4500);
insert into public.product(name,price) values('Pantech vega Express',4400);
insert into public.product(name,price) values('Huawei IDEOS X6',4300);
insert into public.product(name,price) values('Altek Leo',4200);
insert into public.product(name,price) values('Oppo',4100);
insert into public.product(name,price) values('Samsung Galaxy S2',4000);
insert into public.product(name,price) values('Gigabyte Gsmart Rola',3900);
insert into public.product(name,price) values('LG Optimus 2X',3800);
insert into public.product(name,price) values('LG Optimus Black',3700);
insert into public.product(name,price) values('Motorola Atrix 4G',3600);
insert into public.product(name,price) values('Motorola Bionic',3500);
insert into public.product(name,price) values('Samsung Infuse 4G',3400);
insert into public.product(name,price) values('Sony Ericsson Xperia arc',3300);
insert into public.product(name,price) values('Acer E210',3200);
insert into public.product(name,price) values('Acer liquidmini',3100);
insert into public.product(name,price) values('LG thrive',3000);
insert into public.product(name,price) values('Samsung Galaxy Pro',2900);
insert into public.product(name,price) values('LG revolution 4G',2800);
insert into public.product(name,price) values('LG optimus big',2700);
insert into public.product(name,price) values('Sony Xperia Play',2600);
insert into public.product(name,price) values('ViewSonic ViewPad 4',2500);
insert into public.product(name,price) values('Samsung Galaxy S Ace',2400);
insert into public.product(name,price) values('Samsung Galaxy Fit',2300);
insert into public.product(name,price) values('Samsung Galaxy Gio',2200);
insert into public.product(name,price) values('Samsung Galaxy Mini',2100);
insert into public.product(name,price) values('Kyocera Echo',2000);
insert into public.product(name,price) values('OliveSmart V-S300',1900);
insert into public.product(name,price) values('Viewsonic V350',1800);
insert into public.product(name,price) values('LG optimum 3D',1700);
insert into public.product(name,price) values('Sony XPERIA Pro',1600);
insert into public.product(name,price) values('Sony XPERIA Neo',1500);
insert into public.product(name,price) values('Motorola Pro',1400);
insert into public.product(name,price) values('Acer Iconia Smart',1300);
insert into public.product(name,price) values('ZTE skate',1200);
insert into public.product(name,price) values('ZTE Amigo',1100);
insert into public.product(name,price) values('Huawei IDEO X3',1000);
insert into public.product(name,price) values('HTC incredible S',900);
insert into public.product(name,price) values('HTC droid incredible 2',800);
insert into public.product(name,price) values('HTC wildfire S',700);
insert into public.product(name,price) values('HTC ChaCha',600);
insert into public.product(name,price) values('HTC Salsa',500);
insert into public.product(name,price) values('HTC desire S',400);
insert into public.product(name,price) values('HTC Merge',300);
insert into public.product(name,price) values('Umeox Apolla',200);
insert into public.product(name,price) values('Millennius Apanda A100',8965);
insert into public.product(name,price) values('Nec MEDIAS E-04C',8990);
insert into public.product(name,price) values('Nec MEDIAS WP N-06C',9015);
insert into public.product(name,price) values('T-Mobile Sidekick 4G',9040);
insert into public.product(name,price) values('INQ Cloud Touch',9065);
insert into public.product(name,price) values('HTC EVO 3D',9090);
insert into public.product(name,price) values('Samsung Droid Charge',9115);
insert into public.product(name,price) values('Samsung Replenish',9140);
insert into public.product(name,price) values('Samsung Restore',9165);
insert into public.product(name,price) values('Sony Ericsson W8 Walkman',9190);
insert into public.product(name,price) values('Casio's G'zOne Commando',9215);
insert into public.product(name,price) values('Motorola XPRT',9240);
insert into public.product(name,price) values('Motorola Titanium',9265);
insert into public.product(name,price) values('Sonyericsson Xperia mini',9290);
insert into public.product(name,price) values('Sonyericsson Xperia mini pro',9315);
insert into public.product(name,price) values('Sharp Aquos Phone SH-12C',9340);
insert into public.product(name,price) values('Vodafone Smart',9365);
insert into public.product(name,price) values('Samsung Exhibit 4G',9390);
insert into public.product(name,price) values('Samsung GT2',9415);
insert into public.product(name,price) values('INFOBAR A01',9440);
insert into public.product(name,price) values('Sharp Aquos Hybrid 007sh',9465);
insert into public.product(name,price) values('Pantech Crossover',9490);
insert into public.product(name,price) values('LG Gensis',9515);
insert into public.product(name,price) values('TAKE Janus KM-S200',9540);
insert into public.product(name,price) values('Motorola XT882',9565);
insert into public.product(name,price) values('Motolroa Photon 4G',9590);
insert into public.product(name,price) values('Motorola Triumph',9615);
insert into public.product(name,price) values('Huawei X1',9640);
insert into public.product(name,price) values('ZTE Libra',9665);
insert into public.product(name,price) values('Samsung Galaxy Prevail',9690);
insert into public.product(name,price) values('Samsung Dart',9715);
insert into public.product(name,price) values('Motorola XT316',9740);
insert into public.product(name,price) values('LG optimus Pro LG-C660',9765);
insert into public.product(name,price) values('LG optimus Net LG-C690',9790);
insert into public.product(name,price) values('Samsung Galaxy R',9815);
insert into public.product(name,price) values('HTC Sensation',9840);
insert into public.product(name,price) values('Motorola Defy+',9865);
insert into public.product(name,price) values('Sony Ericsson Live with walkman',9890);
insert into public.product(name,price) values('Samsung Admire',9915);
insert into public.product(name,price) values('Samsung Galaxy W',9940);
insert into public.product(name,price) values('Samsung Galaxy M Pro',9965);
insert into public.product(name,price) values('Samsung Galaxy Y',9990);
insert into public.product(name,price) values('Motorola Pro+',10015);
insert into public.product(name,price) values('Samsung Galaxy Note',10040);
insert into public.product(name,price) values('Huawei Impulse 4G',10065);
insert into public.product(name,price) values('Samsung Vitality',10090);
insert into public.product(name,price) values('LG Enlighten',10115);
insert into public.product(name,price) values('HTC Raider',10140);
insert into public.product(name,price) values('Samsung Galaxy S II LTE',10165);
insert into public.product(name,price) values('Samsung Galaxy S II HD LTE',10190);
insert into public.product(name,price) values('Fujitsu Arrows Z ISW11F',10215);
insert into public.product(name,price) values('HTC Amaze 4G',10240);
insert into public.product(name,price) values('LG optimus EX',10265);
insert into public.product(name,price) values('HTC explorer',10290);
insert into public.product(name,price) values('HTC rhyme',10315);
insert into public.product(name,price) values('Disney DM010SH',10340);
insert into public.product(name,price) values('Disney DM011SH',10365);
insert into public.product(name,price) values('Sony Xperia Ray',10390);
insert into public.product(name,price) values('Dell Streak Pro',10415);
insert into public.product(name,price) values('LG Optimus LTE',10440);
insert into public.product(name,price) values('HTC Sensation XE',10465);
insert into public.product(name,price) values('Motorola Atrix 2',10490);
insert into public.product(name,price) values('Samsung doubletime',10515);
insert into public.product(name,price) values('Samsung Captivate Glide',10540);
insert into public.product(name,price) values('Pantech Pocket',10565);
insert into public.product(name,price) values('ZTE Avail',10590);
insert into public.product(name,price) values('Motorola Droid Razr',10615);
insert into public.product(name,price) values('Galaxy Nexus',10640);
insert into public.product(name,price) values('Motorola Admiral',10665);
insert into public.product(name,price) values('Samsung Exhibit II 4G',10690);
insert into public.product(name,price) values('HUAWEI Deuce',10715);
insert into public.product(name,price) values('HTC Vivid',10740);
insert into public.product(name,price) values('Samsung Galaxy S II Skyrocket',10765);
insert into public.product(name,price) values('HTC Sensation XL',10790);
insert into public.product(name,price) values('HTC Rezound',10815);
insert into public.product(name,price) values('Samsung Repp',10840);
insert into public.product(name,price) values('LG Gossip Pro',10865);
insert into public.product(name,price) values('Verzo Kinzo',10890);
insert into public.product(name,price) values('LG Nitro HD',10915);
